[users.mb_north]
password = "Aurora#N28!Wave"
region = "North"

[users.mb_east]
password = "Lotus@E54!River"
region = "East"

[users.mb_west]
password = "Falcon!W73@Stone"
region = "West"

[users.mb_south]
password = "Coral@S91!Forest"
region = "South"